# Evaluate
The evaluation is done after the training, not during the training. This is because the evaluation can then be executed on a seperate computer with less resources, while the powerful computers continue training. Two dataloaders are created, one for the 2-class dataset and one for the 8-class dataset. The validation set is used to calculate the common metrics, which are then stored in a .pickle file, which are used in 4 to analyse and graph the results.  

In [2]:
import evaluate
import glob
import gc
import torch

In [3]:
dataloader = evaluate.get_dataloader(2)

val2: Scanning 'KITTI\yolo2\val.cache' images and labels... 2244 found, 0 missing, 0 empty, 0 corrupted: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2244/2244 [00:00<?, ?it/s]

C:\Users\Jelte\PycharmProjects\ALFL-clean


val2: Scanning 'KITTI\yolo2\val.cache' images and labels... 2244 found, 0 missing, 0 empty, 0 corrupted: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2244/2244 [00:00<?, ?it/s]


In [4]:
evaluate.evaluate('pseudo_fl/fed-12-280.pt', None, None, dataloader, 2)

YOLOv5  5639932 torch 1.8.0+cu111 CUDA:0 (GeForce RTX 3080, 10240.0MB)

Fusing layers... 
Model Summary: 224 layers, 7056607 parameters, 0 gradients
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:15<00:00,  2.27it/s]



saving json runs\val\fed-12-280\fed-12-280_predictions.json...
                 all        2244       10080       0.797       0.686       0.753       0.403
                 car        2244        8748       0.867       0.828       0.893       0.562
          pedestrian        2244        1332       0.727       0.543       0.613       0.244


((0.7973857093665015,
  0.6855405413755431,
  0.7531716917426254,
  0.4030898796118148,
  0.036653388291597366,
  0.04719178006052971,
  0.0010762033052742481),
 array([    0.56187,      0.2443]),
 1627586715.8881018,
 {'p': array([    0.86745,     0.72732]),
  'r': array([    0.82842,     0.54266]),
  'ap': array([    0.56187,      0.2443]),
  'f1': array([    0.84749,     0.62157]),
  'ap_class': array([0, 1]),
  'ap50': array([    0.89337,     0.61297]),
  'mp': 0.7973857093665015,
  'mr': 0.6855405413755431,
  'map50': 0.7531716917426254,
  'map': 0.4030898796118148,
  'nt': array([8748, 1332], dtype=int64),
  'names': {0: 'car', 1: 'pedestrian'},
  'res_per_class': [('car',
    2244,
    8748,
    0.867454642237468,
    0.8284179240969365,
    0.8933718715658732,
    0.5618748728565351),
   ('pedestrian',
    2244,
    1332,
    0.727316776495535,
    0.5426631586541497,
    0.6129715119193777,
    0.24430488636709446)],
  'conf_matrix': array([[       7668,           3,        22

In [3]:
evaluate.evaluate('pseudo_fl/fed-12-200.pt', None, None, dataloader, 2)

YOLOv5  5639932 torch 1.8.0+cu111 CUDA:0 (GeForce RTX 3080, 10240.0MB)

Fusing layers... 
Model Summary: 224 layers, 7056607 parameters, 0 gradients
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:15<00:00,  2.32it/s]



saving json runs\val\fed-12-200\fed-12-200_predictions.json...
                 all        2244       10080       0.776       0.699       0.749       0.401
                 car        2244        8748       0.839       0.845       0.889       0.561
          pedestrian        2244        1332       0.713       0.553       0.609       0.242


((0.7757478192206549,
  0.6993768459817843,
  0.7489088930854142,
  0.4014253977873569,
  0.03673572465777397,
  0.04773494601249695,
  0.001078975386917591),
 array([    0.56111,     0.24174]),
 1627563495.0057209,
 {'p': array([    0.83874,     0.71276]),
  'r': array([    0.84545,      0.5533]),
  'ap': array([    0.56111,     0.24174]),
  'f1': array([    0.84208,     0.62299]),
  'ap_class': array([0, 1]),
  'ap50': array([    0.88882,     0.60899]),
  'mp': 0.7757478192206549,
  'mr': 0.6993768459817843,
  'map50': 0.7489088930854142,
  'map': 0.4014253977873569,
  'nt': array([8748, 1332], dtype=int64),
  'names': {0: 'car', 1: 'pedestrian'},
  'res_per_class': [('car',
    2244,
    8748,
    0.8387362298395743,
    0.8454503886602652,
    0.8888245039975653,
    0.5611081534949793),
   ('pedestrian',
    2244,
    1332,
    0.7127594086017356,
    0.5533033033033034,
    0.608993282173263,
    0.24174264207973448)],
  'conf_matrix': array([[       7763,           2,        247

In [3]:
evaluate.evaluate('pseudo_fl/fed-12-200.pt', None, None, dataloader, 2)

YOLOv5  5639932 torch 1.8.0+cu111 CUDA:0 (GeForce RTX 3080, 10240.0MB)

Fusing layers... 
Model Summary: 224 layers, 7056607 parameters, 0 gradients
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:16<00:00,  2.20it/s]



saving json runs\val\fed-12-121\fed-12-121_predictions.json...
                 all        2244       10080       0.779       0.674       0.745       0.391
                 car        2244        8748       0.834       0.825       0.887       0.546
          pedestrian        2244        1332       0.725       0.523       0.603       0.236


((0.7793613773252648,
  0.6736047318466157,
  0.7450895779553562,
  0.3906007434822122,
  0.037519458681344986,
  0.04604988545179367,
  0.0010285453172400594),
 array([    0.54552,     0.23568]),
 1627513494.777964,
 {'p': array([      0.834,     0.72473]),
  'r': array([    0.82469,     0.52252]),
  'ap': array([    0.54552,     0.23568]),
  'f1': array([    0.82932,     0.60723]),
  'ap_class': array([0, 1]),
  'ap50': array([    0.88734,     0.60284]),
  'mp': 0.7793613773252648,
  'mr': 0.6736047318466157,
  'map50': 0.7450895779553562,
  'map': 0.3906007434822122,
  'nt': array([8748, 1332], dtype=int64),
  'names': {0: 'car', 1: 'pedestrian'},
  'res_per_class': [('car',
    2244,
    8748,
    0.8339953737837106,
    0.824686941170709,
    0.8873396108267833,
    0.5455226080248707),
   ('pedestrian',
    2244,
    1332,
    0.724727380866819,
    0.5225225225225225,
    0.6028395450839292,
    0.23567887893955364)],
  'conf_matrix': array([[       7638,           2,        248

## Evaluating 2-class sets

In [2]:
dataloader = evaluate.get_dataloader(2)

C:\Users\Jelte\PycharmProjects\ALFL-clean


val2: Scanning 'KITTI\yolo2\val.cache' images and labels... 2244 found, 0 missing, 0 empty, 0 corrupted: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2244/2244 [00:00<?, ?it/s]


In [ ]:
for file in glob.glob('runs/*/weights/best.pt'):
    evaluate.evaluate(file, None, None, dataloader, 2)
    gc.collect()
    torch.cuda.empty_cache()

## Evaluating 8-class sets

In [ ]:
dataloader = create_dataloader(f'KITTI/yolo8/val.txt', imgsz, batch_size, gs, opt, pad=0.5, rect=True, prefix=colorstr('val8: '))[0]

In [ ]:
nc = 8
for file in glob.glob("D:\\Research Project\\8_Chained\\Runs\\*\\weights\\best.pt", recursive=True):
    evaluate.evaluate(file, None, None, dataloader, 8)
    gc.collect()
    torch.cuda.empty_cache()